FROM otel/opentelemetry-collector-contrib:0.88.0 AS collector

FROM alpine:3.18
RUN apk add --no-cache wget ca-certificates
COPY --from=collector /otelcol-contrib /otelcol-contrib
ENTRYPOINT ["/otelcol-contrib"]
